# Generated by Django 4.2.3 on 2023-12-30 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_remove_mailing_massage_message_mailing_message_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='mailing',
        ),
        migrations.AddField(
            model_name='mailing',
            name='massage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.message'),
        ),
    ]
